const Cards = [
  {
    type: "club",
    number: 1,
    image: require("./assets/card_club_1.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 2,
    image: require("./assets/card_club_2.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 3,
    image: require("./assets/card_club_3.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 4,
    image: require("./assets/card_club_4.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 5,
    image: require("./assets/card_club_5.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 6,
    image: require("./assets/card_club_6.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 7,
    image: require("./assets/card_club_7.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 8,
    image: require("./assets/card_club_8.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 9,
    image: require("./assets/card_club_9.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 10,
    image: require("./assets/card_club_10.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 11,
    image: require("./assets/card_club_11.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 12,
    image: require("./assets/card_club_12.png"),
    isdeleted: false,
  },
  {
    type: "club",
    number: 13,
    image: require("./assets/card_club_13.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 1,
    image: require("./assets/card_spade_1.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 2,
    image: require("./assets/card_spade_2.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 3,
    image: require("./assets/card_spade_3.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 4,
    image: require("./assets/card_spade_4.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 5,
    image: require("./assets/card_spade_5.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 6,
    image: require("./assets/card_spade_6.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 7,
    image: require("./assets/card_spade_7.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 8,
    image: require("./assets/card_spade_8.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 9,
    image: require("./assets/card_spade_9.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 10,
    image: require("./assets/card_spade_10.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 11,
    image: require("./assets/card_spade_11.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 12,
    image: require("./assets/card_spade_12.png"),
    isdeleted: false,
  },
  {
    type: "spade",
    number: 13,
    image: require("./assets/card_spade_13.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 1,
    image: require("./assets/card_heart_1.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 2,
    image: require("./assets/card_heart_2.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 3,
    image: require("./assets/card_heart_3.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 4,
    image: require("./assets/card_heart_4.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 5,
    image: require("./assets/card_heart_5.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 6,
    image: require("./assets/card_heart_6.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 7,
    image: require("./assets/card_heart_7.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 8,
    image: require("./assets/card_heart_8.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 9,
    image: require("./assets/card_heart_9.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 10,
    image: require("./assets/card_heart_10.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 11,
    image: require("./assets/card_heart_11.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 12,
    image: require("./assets/card_heart_12.png"),
    isdeleted: false,
  },
  {
    type: "heart",
    number: 13,
    image: require("./assets/card_heart_13.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 1,
    image: require("./assets/card_diamond_1.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 2,
    image: require("./assets/card_diamond_2.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 3,
    image: require("./assets/card_diamond_3.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 4,
    image: require("./assets/card_diamond_4.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 5,
    image: require("./assets/card_diamond_5.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 6,
    image: require("./assets/card_diamond_6.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 7,
    image: require("./assets/card_diamond_7.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 8,
    image: require("./assets/card_diamond_8.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 9,
    image: require("./assets/card_diamond_9.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 10,
    image: require("./assets/card_diamond_10.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 11,
    image: require("./assets/card_diamond_11.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 12,
    image: require("./assets/card_diamond_12.png"),
    isdeleted: false,
  },
  {
    type: "diamond",
    number: 13,
    image: require("./assets/card_diamond_13.png"),
    isdeleted: false,
  },
];

export const cards = Cards;
